
#ifndef IEvents_h
#define IEvents_h

#include <stdbool.h>
#include "matiasBrosGame.h"
#define MAXIMOEVENTOSBUFFER 40
#define LIMITEMOVDEPALANCA 100
#define VACIO 0
#define NOPRESSED 0
#define PRESSED 1

enum { NOHAYMOVIMIENTO = 50, UPDERECHA, DOWNDERECHA, UPABAJODERECHA, DOWNABAJODERECHA, UPABAJO, DOWNABAJO, UPABAJOIZQUIERDA, DOWNABAJOIZQUIERDA,
        UPIZQUIERDA, DOWNIZQUIERDA, UPARRIBAIZQUIERDA, DOWNARRIBAIZQUIERDA, UPARRIBA, DOWNARRIBA, UPARRIBADERECHA, DOWNARRIBADERECHA, UPBOTON, DOWNBOTON };
enum { DOWN_A=101, DOWN_B, DOWN_C, DOWN_D, DOWN_E, DOWN_F, DOWN_G, DOWN_H, DOWN_I, DOWN_J, DOWN_K, DOWN_L, DOWN_M, DOWN_N, DOWN_Ñ, 
      DOWN_O, DOWN_P, DOWN_Q, DOWN_R, DOWN_S, DOWN_T, DOWN_U, DOWN_V, DOWN_W, DOWN_X, DOWN_Y, DOWN_Z };


char getInputEvent (void); /* ESTA ES LA FUNCION POR LA CUAL SE LEERAN LOS EVENTOS DE ENTRADA DEL BUFFER, LAS CORRESPONDIENTES SE IDENTIFICAN CON LAS
 CONSTANTES DE ARRIBA */

void * InputEvent(void *); //ESTA ES LA FUNCION QUE SE VA A ASOCIAR AL THREAD CORRESPONDIENTE

void storeInputEvent (char evento); //ESTA FUNCION GUARDA UN EVENTO EN EL BUFFER, PUEDE SER UTIL PUBLICARLA PARA FORZARLE EVENTOS EXTERNOS AL JOYSTICK

int esBufferVacio (void); //DEVUELVE 1 EN EL CASO DE QUE EL BUFFER ESTE VACIO, 1 EN EL CASO CONTRARIO

void * keyboardChanges (void* UnusedP);

int mouseChanges(bool estado, int evMouseX, int evMouseY);

void actualizarDisplay(char matriz[16][16] ); //ESTA FUNCION CONTROLA EL BUFFER  DEL DISPLAY A PARTIR DE LA MATRIZ DADA
// SI EL ELEMENTO EN LA MATRIZ VALE 0, SE APAGA EL LED CORRESPONDIENTE Y
// SI VALE 1 SE LO PRENDE
// EN CUALQUIER OTRO CASO, SE LO DEJA IGUAL QUE ANTES

#endif //IEvents_h
